easy_admin:
    design:
        brand_color: 'purple'
    entities:
        Encuesta:
            class: App\Entity\Encuesta
            list:
                fields:
                    - title
                    - { property: 'img', type: 'image', base_path: '../../img' }
                    - img
                    - preguntas
                    - resultados
                    - comentarios
            show:
                fields:
                    - title
                    - { property: 'img', type: 'image', base_path: '../../img' }
                    - img
                    - preguntas
                    - resultados
                    - comentarios
            form:
                fields:
                    - title
                    - { property: 'imageFile', type: 'vich_image' }
                    - preguntas
                    - resultados
                    - comentarios
            edit:
                fields:
                    - title
                    - { property: 'imageFile', type: 'vich_image' }
                    - preguntas
                    - resultados
                    - comentarios

        Sorteo:
            class: App\Entity\Sorteo
            form:
                fields:
                    - premio
                    - img
                    - fecha
                    - usuarios
                    - ganador
        Usuario:
            class: App\Entity\Usuario
            form:
                fields:
                    - nombre
                    - email
                    - password
                    - sorteos
                    - sorteos_ganados
        Pregunta:
            class: App\Entity\Pregunta
            form:
                fields:
                    - image
                    - { property: 'text', type : 'textarea' }
                    - encuesta
                    - respuestas
        Respuesta:
            class: App\Entity\Respuesta
            form:
                fields:
                    - { property: 'text', type : 'textarea' }
                    - value
                    - pregunta
        Resultado:
            class: App\Entity\Resultado
            form:
                fields:
                    - { property: 'text', type : 'textarea' }
                    - image
                    - { property: 'explanation', type : 'textarea' }
                    - { property: 'min_val', type : 'integer' }
                    - { property: 'max_val', type : 'integer' }
                    - encuesta
        Comentario:
            class: App\Entity\Comentario
            form:
                fields:
                    - { property: 'text', type : 'textarea' }
                    - encuesta
        Premio:
            class: App\Entity\Premio
            form:
                fields:
                    - title
                    - imagen
                    - sorteos
