easy_admin:
  list:
    title: 'Lista de %%entity_label%%s'
  edit:
    title: 'Editar %%entity_label%%'
  new:
    title: 'Añadir %%entity_label%%'
  site_name: 'Secret Backend'
  design:
    brand_color: 'purple'
  entities:
    Encuesta:
      class: App\Entity\Encuesta
      label: 'Encuesta'
      form:
        fields: ['title', 'img']

    Pregunta:
      class: App\Entity\Pregunta
      label: 'Pregunta'
      form:
        fields: ['image', 'text', 'encuesta']

    Comentario: 
      class: App\Entity\Comentario
      label: 'Comentario'

    Premio:
      class: App\Entity\Premio
      label: 'Premio'
      form:
        fields: ['title', 'imagen']

    Respuesta:
      class: App\Entity\Respuesta
      label: 'Respuesta'
      form:
        fields:
          - text
          - value
          - { property: pregunta, type_options: { choice_label: 'text' } }
    Resultado:
      class: App\Entity\Resultado
      label: 'Resultado'
      form:
        fields: ['text', 'image', 'explanation', 'minVal', 'maxVal', 'encuesta']
    Sorteo: 
      class: App\Entity\Sorteo
      label: 'Sorteo'
      help: 'Para añadir un ganador al sorteo editalo una vez creado!'
      form:
        fields: ['img', 'fecha', 'premio']
      edit:
        fields: ['ganador']
    Usuario:
      class: App\Entity\Usuario
      label: 'Usuario'
      form:
        fields: ['nombre', 'email', 'password']

