easy_admin:
  list:
    title: 'Lista de %%entity_label%%s'
  edit:
    title: 'Editar %%entity_label%%'
  new:
    title: 'Añadir %%entity_label%%'
  site_name: 'Secret Backend'
  design:
    brand_color: 'purple'
  entities:
    Poll:
      class: App\Entity\Poll
      label: 'Poll'
      form:
        fields: ['title', 'img']

    Question:
      class: App\Entity\Question
      label: 'Question'
      form:
        fields: ['image', 'text', 'poll']

    Comment: 
      class: App\Entity\Comment
      label: 'Comment'

    Prize:
      class: App\Entity\Prize
      label: 'Prize'
      form:
        fields: ['title', 'imagen']

    Answer:
      class: App\Entity\Answer
      label: 'Answer'
      form:
        fields:
          - text
          - value
          - { property: question, type_options: { choice_label: 'text' } }
    Result:
      class: App\Entity\Result
      label: 'Result'
      form:
        fields: ['text', 'image', 'explanation', 'minVal', 'maxVal', 'poll']
    Lottery: 
      class: App\Entity\Lottery
      label: 'Lottery'
      help: 'Para añadir un ganador al lottery editalo una vez creado!'
      form:
        fields: ['img', 'fecha', 'prize']
      edit:
        fields: ['ganador']
    User:
      class: App\Entity\User
      label: 'User'
      form:
        fields: ['nombre', 'email', 'password']

