parameters:
    app.path.encuesta_imgs: /img

vich_uploader:
    db_driver: orm

    mappings:
        encuesta_imgs:
            uri_prefix: '%app.path.encuesta_imgs%'
            upload_destination: '%kernel.root_dir%/../img'
