parameters:
    app.path.poll_imgs: /img

vich_uploader:
    db_driver: orm

    mappings:
        poll_imgs:
            uri_prefix: '%app.path.poll_imgs%'
            upload_destination: '%kernel.root_dir%/../img'
